@url_dev=http://localhost:3056/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: asdfasdfasdfasdf

{
    "name": "tangthienantedst1d",
    "email": "tanasd@gmddddfad1idgsddl.com",
    "password": "abc1asdddf23"
}